name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build ${{ matrix.arch }}
        # Build Release Apk
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assemblerelease -Darch=${{ matrix.arch }}

      - name: Upload ${{matrix.arch}}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher2 ${{ matrix.arch }}
          # Only allow APK files
          path: ZalithLauncher/build/outputs/apk/release/*.apk